language: shell

services:
  - docker

before_install: bash -c 'shopt -s globstar; shellcheck *.sh'

script: bash build.sh

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master

notifications:
  email:
    recipients:
      - mickiller.25@gmail.com
    on_success: never
    on_failure: always
